require('_plugins/settings/toggleterm')
require('_plugins/settings/ddc')
require('_plugins/settings/nvim_tree')
require('_plugins/settings/telescope')
require('_plugins/settings/vim_terraform')
require('_plugins/settings/lualine')
