require('plugin_settings/plugin_settings_toggleterm')
require('plugin_settings/plugin_settings_ddc')
require('plugin_settings/plugin_settings_nvim_tree')
require('plugin_settings/plugin_settings_telescope')
require('plugin_settings/plugin_settings_vim_terraform')
